# 使用外部标定文件的配置示例
# 此配置跳过本地标定，直接使用从OpenCap官网下载的标定文件

calibration:
  # 启用外部标定文件
  use_external_calibration: true

  # 指定每个摄像头的外部标定文件路径
  # 请根据实际情况修改路径
  external_calibration_files:
    Cam1: "e:/guge/opencap-core-local/Data/OpenCapData_a285e8cf-f14b-403d-969f-3be4f50a8161_6ab4593e-38a4-4eb1-8f45-76e9a5c6b0a9/Videos/Cam1/cameraIntrinsicsExtrinsics.pickle"
    Cam2: "e:/guge/opencap-core-local/Data/OpenCapData_a285e8cf-f14b-403d-969f-3be4f50a8161_6ab4593e-38a4-4eb1-8f45-76e9a5c6b0a9/Videos/Cam0/cameraIntrinsicsExtrinsics.pickle"

  checkerboard:
    dimensions:
    - 13
    - 8
    square_size: 60
    placement: backWall

  deployed_folders:
  - Deployed_720_60fps
  - Deployed
  n_images: 50
  interactive_selection: false

directories:
  calibration_videos: ./LocalData/Calibration
  input_videos: ./LocalData/Videos
  output: ./LocalData/Results

output:
  delete_intermediate: false
  generate_opensim: true
  save_videos: true

processing:
  augmenter_model: v0.3
  bbox_threshold: 0.8
  filter_frequency: default
  framerate: 30
  image_upsample_factor: 4
  pose_detector: mmpose
  resolution: 1x736
  scaling_setup: upright_standing_pose

session:
  description: 使用外部标定文件的OpenCap会话
  name: session_external_calib
  subject_height: 170.0
  subject_mass: 67.0