calibration:
  checkerboard:
    dimensions:
    - 8
    - 5
    square_size: 35
 

    # 棋盘格放置方式 - 非常重要，直接影响坐标系转换！
    # 选项:
    #   backWall - 棋盘格垂直放置在背景墙上（默认，推荐）
    #   ground - 棋盘格水平放置在地面上
    #   Perpendicular - 同backWall，垂直放置
    #   Lying - 同ground，水平放置
    # 注意: 此设置决定了从运动捕获坐标系到OpenSim坐标系的转换方式
    # 错误的设置可能导致OpenSim中人物倒置或姿态异常
    placement: backWall
  deployed_folders:
  - Deployed_720_60fps
  - Deployed
  n_images: 50
  # 启用交互式标定方案选择 - 重要：确保Z轴指向标定板内部
  # 注意：只在标定试验时选择一次，后续静态和动态试验会自动使用保存的选择
  interactive_selection: true
  force_correct_orientation: false  # 信任自动倒置检测，不强制覆盖

  # 标定方案选择 (针对每个摄像头，指定使用方案0还是方案1)
  # 格式: 摄像头名称: 方案编号 (0或1)
  # 如果不指定，默认使用方案0
  # 重要：根据OpenCap最佳实践，选择使Z轴(深蓝色箭头)指向标定板内部的方案
  # 注意：如果启用了interactive_selection，此设置将被忽略，由用户交互式选择
  extrinsic_solutions:
    # Cam1: 0  # 使用方案0 (默认)
    # Cam2: 1  # 使用方案1 (备选) - 如果默认方案的Z轴方向错误
directories:
  calibration_videos: ./LocalData/Calibration
  input_videos: ./LocalData/Videos
  output: ./LocalData/Results
output:
  delete_intermediate: false
  generate_opensim: true
  save_videos: true
processing:
  augmenter_model: v0.3
  bbox_threshold: 0.8
  filter_frequency: default
  framerate: 30
  image_upsample_factor: 4
  pose_detector: OpenPose
  resolution: 1x736
  scaling_setup: upright_standing_pose
session:
  description: 本地OpenCap会话
  name: LocalSession_20250907_172019
  subject_height: 173.0
  subject_mass: 78.0
