calibration:
  checkerboard:
    dimensions:
    - 5
    - 4
    square_size: 35
  deployed_folders:
  - Deployed_720_60fps
  - Deployed
  n_images: 50
directories:
  calibration_videos: ./LocalData/Calibration
  input_videos: ./LocalData/Videos
  output: ./LocalData/Results
output:
  delete_intermediate: false
  generate_opensim: true
  save_videos: true
processing:
  augmenter_model: v0.3
  bbox_threshold: 0.8
  filter_frequency: default
  framerate: 30
  image_upsample_factor: 4
  pose_detector: OpenPose
  resolution: 1x736
  scaling_setup: upright_standing_pose
session:
  description: 本地OpenCap会话
  name: LocalSession_20250907_172019
  subject_height: 170.0
  subject_mass: 67.0
